openapi: 3.0.3
info:
  title: User Service API
  description: API definition for the User dataset used in the Customer Data Platform (CDP) pipeline.
  version: 1.0.0

servers:
  - url: http://localhost:8083
    description: Local User Service

components:
  schemas:
    Review:
      type: object
      description: User review of a product
      properties:
        id:
          type: string
          description: Unique event identifier
          example: "E00001234"
        order:
          type: string
          description: order id
        product:
          type: string
          description: Product ID
        user:
          type: string
          description: user id
        rating:
          type: number
          description: Timestamp of the event
          example: 5
        reviewText:
          type: string
          description: Timestamp of the event
          example: "this is a string"
        reviewDate:
          type: string
          format: date-time
          description: Timestamp of the event
          example: "2025-11-19T14:23:41"